/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#bec6e0",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#131b2e",
        "secondary-fixed-dim": "#c0c1ff",
        "error-container": "#ffdad6",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#e3dfff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#07006c",
        "on-error": "#ffffff",
        "on-primary-fixed": "#100069",
        "secondary-fixed": "#e1e0ff",
        "on-secondary-container": "#fffbff",
        "primary-container": "#4338ca",
        "on-primary-container": "#c1beff",
        "on-surface": "#191c1e",
        "secondary-container": "#6063ee",
        "background": "#f7f9fb",
        "tertiary-fixed": "#dae2fd",
        "surface-tint": "#5148d7",
        "primary-fixed-dim": "#c3c0ff",
        "outline": "#777586",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "outline-variant": "#c7c4d7",
        "surface": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-surface-variant": "#464554",
        "inverse-primary": "#c3c0ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#bcc4de",
        "inverse-surface": "#2d3133",
        "secondary": "#4648d4",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-container-low": "#f2f4f6",
        "primary": "#2a14b4",
        "surface-container": "#eceef0",
        "tertiary-container": "#495167",
        "surface-container-high": "#e6e8ea",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "error": "#ba1a1a",
        "surface-dim": "#d8dadc",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#372abf",
        "tertiary": "#323a4f"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1440px",
        "unit": "4px",
        "stack-sm": "8px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
};
